@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTYxMTYwNzF9.OeVNBp4_-76CdfhKbCe5qN29iJOffLq_6J7P12N6Pac

### Movies Index
get http://localhost:3000/movies.json

### Movies Show
get http://localhost:3000/movies/3.json 

### User Create
post http://localhost:3000/users.json
Content-Type: application/json

{
  "username": "testy",
  "email": "testy@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Users Index
get http://localhost:3000/users.json 

### User Show
get http://localhost:3000/users/2

### User Destroy
delete http://localhost:3000/users/3.json
Authorization: Bearer {{jwt}}

### RatedMovie Index
get http://localhost:3000/rated_movies.json

### RatedMovie Create 
post http://localhost:3000/rated_movies.json 
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "rating": 5.7,
  "message": "A lot to be desired",
  "movie_id": 1
}

### RatedMovie Show
get  http://localhost:3000/rated_movies/3.json

### RatedMovie Destroy
delete http://localhost:3000/rated_movies/2.json
Authorization: Bearer {{jwt}}

### Sessions Create (Login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "username": "test",
  "password": "password"
}